# Generated by Django 3.1 on 2020-11-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=74)),
                ('image', models.CharField(max_length=300)),
                ('heading_2', models.CharField(blank=True, max_length=74, null=True)),
                ('image_2', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_1', models.TextField(blank=True, max_length=2000, null=True)),
                ('paragraph_2', models.TextField(blank=True, max_length=2000, null=True)),
                ('paragraph_3', models.TextField(blank=True, max_length=2000, null=True)),
                ('paragraph_4', models.TextField(blank=True, max_length=2000, null=True)),
                ('paragraph_5', models.TextField(blank=True, max_length=2000, null=True)),
                ('paragraph_6', models.TextField(blank=True, max_length=2000, null=True)),
                ('tag_1', models.CharField(blank=True, max_length=20, null=True)),
                ('tag_2', models.CharField(blank=True, max_length=20, null=True)),
                ('tag_3', models.CharField(blank=True, max_length=20, null=True)),
                ('tag_4', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
