# Generated by Django 3.1 on 2020-11-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='heading_3',
            field=models.CharField(blank=True, max_length=74, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
